export const defaultDetailPaneSize = '30%';
export const emailDomain = 'aloft.ai';
export const baseUrl = `https://www.${emailDomain}`;
export const aboutLink = `${baseUrl}/b4ufly/about-aloft`;
export const termsLink = `${baseUrl}/b4ufly/terms`;
export const DETAIL_PANE_SIZE = 'DETAIL_PANE_SIZE';
export const MAPBOX_TOKEN = 'mapboxAccessToken';
export const ALOFT_TOKEN = 'aloftToken';
export const ALOFT_API_URL = 'aloftApiUrl'
export const defaultAloftApiUrl = 'https://api.laanc.aloft.link/v1/airspace/layers' //TODO replace with prod url